apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    services: "5"
    configmaps: "5"
    secrets: "5"
    persistentvolumeclaims: "3"
    requests.cpu: "3"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
