apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    pods: "20"
    services: "10"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "5"
    requests.cpu: "10"
    requests.memory: "16Gi"
    limits.cpu: "20"
    limits.memory: "32Gi"
