# app/Dockerfile

FROM python:alpine3.22

WORKDIR /app

# Copia o requirements.txt e instala as dependências
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante da aplicação
COPY . .

# Comando para iniciar a aplicação
CMD ["python", "app.py"]
