# app/Dockerfile

FROM python:3.12-alpine3.22

WORKDIR /app

# Instala dependências do sistema necessárias para compilar psycopg2
RUN apk add --no-cache gcc musl-dev libffi-dev postgresql-dev

# Copia o requirements.txt e instala as dependências Python
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante da aplicação
COPY . .

# Comando para iniciar a aplicação
CMD ["python", "app.py"]
